package cn.css0209.wechat.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`wechat_user`")
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.id
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.login_name
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.username
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.password
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.created_by
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.created_date
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.update_by
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.update_date
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.id
     *
     * @return the value of wechat_user.id
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.id
     *
     * @param id the value for wechat_user.id
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.login_name
     *
     * @return the value of wechat_user.login_name
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.login_name
     *
     * @param loginName the value for wechat_user.login_name
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.username
     *
     * @return the value of wechat_user.username
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.username
     *
     * @param username the value for wechat_user.username
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.password
     *
     * @return the value of wechat_user.password
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.password
     *
     * @param password the value for wechat_user.password
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.created_by
     *
     * @return the value of wechat_user.created_by
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.created_by
     *
     * @param createdBy the value for wechat_user.created_by
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.created_date
     *
     * @return the value of wechat_user.created_date
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.created_date
     *
     * @param createdDate the value for wechat_user.created_date
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.update_by
     *
     * @return the value of wechat_user.update_by
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.update_by
     *
     * @param updateBy the value for wechat_user.update_by
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.update_date
     *
     * @return the value of wechat_user.update_date
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.update_date
     *
     * @param updateDate the value for wechat_user.update_date
     *
     * @mbg.generated Mon Dec 30 15:18:30 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}